# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


issue_9_6 = Issue.create(:title => "The Nth Degree", :volume => 9, :issue_number => 6, :date => DateTime.new(2016, 10, 3))

issue_9_6.articles.create(
    :title => "A Fresh Perspective from a New Kind of Grad Student Senator", 
    :order_number => 1, 
    :image_url => "http://i.imgur.com/7EWJZaX.jpg", 
    :content => "One of the newest members of the Student Senate for 2016-2017 comes from none other than the grad students’ very own Sarayu Sankar. As a second-year Master’s student in Public Service & Administration, Sarayu brings with her a fresh perspective as the only female international grad student senator. While a rookie senator, Sarayu already brings with her a strong reputation from the grad student leaders, including being the only senator to have ever received ringing endorsements from both a previous and current graduate student body president through Marisa Biondi and Paul Taele, respectively.\n\nSince starting her term, Sarayu continues to serve on the Adhoc Diversity committee and Constituency Affairs in the Student Senate, and her coursework in Public Administration has helped her realize the importance of researching any legislation thoroughly and contacting administrators in relevant departments before drafting a Bill. She has also co-sponsored Gig the Vote resolution encouraging early registration and the Spirit of Meditation Bill \"to create an inclusive moment of silence, meditation, or prayer before every meeting.\"\n\nSarayu hopes that with her uniqueness that she can carry over a new message to her fellow student senators. Based on her own observations and input from other grad student leaders, the Off-Campus Senator believes that each senator represents a diverse student population, not one's personal interests. Therefore, she believes that voting on every Bill should be done responsibly, understanding two sides of the issue at hand.\n\nAs for serving on behalf of her constituents, Sarayu expressed that while she is very fortunate to be part of the Aggie community, she also understands that not all grad or international students are as fully invested in Texas A&M’s traditions or public service. In the hopes of having Texas A&M’s school traditions be more inclusive to these populations, Sarayu first aims to invite spirited speakers from Traditions Council for better imparting traditions onto them, and then aims to encourage both grad and international students to be more pro-active in university matters such as assisting in writing and sponsoring university student legislation.\n\n(Pictured: Off-Campus Senator Sarayu Sankar from the Student Senate.)")

issue_9_6.articles.create(
    :title => "An Interdisciplinary Dinner with Drs. Mary and Robert Capraro", 
    :order_number => 2, 
    :image_url => "http://i.imgur.com/vz366Dk.jpg", 
    :content => "This semester's first interdisciplinary dinner was held at the homes of Drs. Mary and Robert Capraro on September 24, 2016. The interdisciplinary dinners are one of GPSC's flagship programs that was started in the Fall of 2013. The main purpose of the dinners is to provide graduate and professional students from across the university an opportunity to interact with faculty members and peers. It is an excellent way to network with people from outside one's department as well.\n\nLocated just outside of College Station, Dr. Capraro's home is a sprawling 12 acres of greenery that their dog, cats, horses, chickens, ducks and deers call home. 15 graduate students from 8 departments spread across 4 colleges participated in the event. Among other things, participants had a chance to exchange their research ideas, discuss the various cultures they come from, eat delicious food and interact with other graduate students in a small and social setting.\n\nDr. Mary and Robert Capraro are no strangers to the interdisciplinary dinners. They hosted a dinner at their homes last semester and so thoroughly enjoyed the experience that they offered to host it again this semester. The GPSC is incredibly thankful for their generosity and hospitality. \n\nIf you know of a faculty who would be willing to host or wish to learn more about how to participate in the event, do not hesitate to reach out to Alisha Ahamed at <a href=\"mailto:vpuniversityaffairs@gpsc.tamu.edu\">vpuniversityaffairs@gpsc.tamu.edu</a>\n\n(Pictured: Drs. Mary and Robert Capraro alongside their grad student dinner guests.)")

issue_9_6.articles.create(
    :title => "PSA President Hina Iftikhar Appointed to MSC Board of Directors", 
    :order_number => 3, 
    :image_url => "http://i.imgur.com/xuj2JJz.jpg", 
    :content => "Biology doctoral student Hina Iftikhar was recently appointed to serve as the international student representative for the Memorial Student Center Board of Directors (MSC BoD) by Graduate Student Body President Paul Taele. The main purpose of the board is to review and recommend general policies that govern the MSC programs, services, and facilities, and the student leadership for the university’s official student union body have a long history of tradition.\n\nThe position itself was newly created in Fall 2015 by the board following a revision to the MSC Constitution for an additional board member, and was in response to the MSC’s diversity plan to include programming to people beyond the traditional domestic undergraduate student audience, such as international, graduate, and professional students. For the 2015-2016 academic year, the first international student representative for the board was held by then-economics Master’s student Jiaojiao Zhang, whom also served as last year’s President of the Chinese Students and Scholars Association.\n\For this academic year, Hina’s successful leadership within the Pakistani Students Association -- including her subsequent role as the organization’s current president -- and the Aggies in Science, Technology and Engineering Policy organization earned her the role as Jiaojiao’s successor. The next board meeting will be held later this month in October, and Hina’s insights on behalf of the international grad students will prove to be invaluable for the current board leadership.\n\n(Pictured: Hina Iftikhar)")

issue_9_6.articles.create(
    :title => "Grad Student Leaders Unite at Annual Student Leader Barbeque", 
    :order_number => 4, 
    :image_url => "http://i.imgur.com/ZserDju.jpg", 
    :content => "On a pleasant Thursday late afternoon of September 29, 2016, over a few hundred attendees ranging from student leaders to university administration were in attendance for the much-awaited 2016 Student Leader Barbecue. This special annual event brought together chief executive officers or representatives of Texas A&M University’s many proud student organizations to visit the senior administrative leadership filled of mingling of like-minded leaders and eating of delicious locally-catered barbeque.\n\nIn attendance at the annual event included a strong contingent of student leaders from the graduate and professional student body, including the executive officers from the student body governments, graduate student associations, diversity-based organizations, and special interest groups. The event was the largest gathering of the year for grad student leaders in particular to congregate and network among themselves -- as well as with their undergrad and senior administrator counterparts -- in a casual environment. In the end, the event was a huge success, and the grad student leaders hope that the event opened up opportunities for further communications and collaborations for the rest of the academic year.\n\n(Pictured: Various grad student leaders at the 2016 Student Leader Barbecue.)")

issue_9_6.articles.create(
    :title => "The Drive to Spotlight Aggie Grad Students’ Research Achievements", 
    :order_number => 5, 
    :image_url => "http://i.imgur.com/BTE4XQf.jpg", 
    :content => "As one of the largest graduate and professional student bodies in the nation spanning over sixteen different colleges, Texas A&M undoubtedly hosts a strong community of talented grad students pursuing state-of-the-art research from many disciplines. However, showcasing those achievements were more recently either constrained at the department- or college-level, or broadcasted less frequently at the grad school-level. Doctoral student Joonhee Kim from Veterinary Physiology and Pharmacology realized this situation during his first year as the Research Committee Co-Chair of the Graduate and Professional Student Council. As a result, Joonhee last year developed a new initiative called the Research Spotlight to better centralize and more frequently celebrate those research achievements from the Aggie grad student body.\n\nFrom the Research Spotlight initiative’s humble beginnings, Joonhee -- alongside fellow Co-Chair Michael Kalan and members of the GPSC Research Committee -- would broadcast these research stories onto the GPSC website. Moreover, the committee would personally seek out notable research stories from various sources such as from awardees of the the seasonal GPSC Travel Award program, competitors of the annual OGAPS 3 Minute Thesis competition, participants of the annual Student Research Week competition, or even word of mouth.\n\nThe Research Spotlight initiative eventually grew to become the most visited section of the GPSC website. Its reputation additionally grew to also include requests directly from the grad school’s research community, as well as becoming a prominent feature in the latest volume of The Nth Degree, which spiritually continues a similar feature from its early digital days back in the late 2000s. The future of the Research Spotlight continues to evolve from its humble beginnings, and Joonhee hopes that the initiative becomes the premier venue for celebrating the amazing research taking place by the Aggie grad student community.\n\n(Pictured: GPSC Reesarch Co-Chair Joonhee Kim)")

issue_9_6.articles.create(
    :title => "Mays Student Alisha Ahamed Appointed as GPSC University Affairs VP", 
    :order_number => 6, 
    :image_url => "http://i.imgur.com/blpYXOC.png", 
    :content => "Early last month, the Graduate and Professional Student Council appointed Alisha Bakhthawar Basheer Ahamed -- a Master’s student in Management Information Systems -- as the new Vice President of University. Initially appointed as Chair of the then-named Multicultural and Diversity Committee for the 2016-2017 academic year, Alisha was later nominated by Graduate Student Body President Paul Taele to serve as interim University Affairs VP shortly after previously elected University Affairs VP Dan Vecellio vacated the position in early Summer 2016.\n\nSince beginning her interim role and eventually receiving approval by the GPSC General Assembly to official status in early 2017, Alisha has made several key moves that has made positive impacts in the academic year so far. Some notable actions include successfully receiving approval from the GPSC General Assembly to rename the Multicultural and Diversity Committee to the Diversity and Inclusion Committee, sitting in several high-level university committees to represent grad students such as Step In, Stand Up and President Young’s Inclusion Council, and has advocated for greater representation for various diversity organizations such as veteran grad students and little-represented religious communities.\n\n(Pictured: GPSC Vice President of University Affairs Alisha Ahamed)")

issue_9_6.articles.create(
    :title => "Research Spotlight: Trey Murphy", 
    :order_number => 7, 
    :image_url => "http://i.imgur.com/uFRCtda.jpg", 
    :content => "In this issue, the graduate student from the Geography Department, Trey Murphy wrote a narrative about his project:\n\n\nI struggle to consider a more dangerous journey than traveling through an active oil and gas boom. During my first trip to the Eagle Ford Shale—one of the most productive oil and gas plays in the United States—in summer 2014, I was constantly jerking the steering wheel to evade the incessant stream of 18-wheelers lurching into oncoming traffic to pass me and whose drivers were ready to make nearly any sacrifice to get their laded trailers to the destinations on schedule. Their immense bravery was only matched by my immeasurable fear. Emotionally wrecked after several hours of driving, I pulled into a rest stop and decided to learn more about the Eagle Ford. It was in that Texas Monthly article that I read about a giddy “elderly rancher who walked into the bank, very pleased to be depositing a $100,000 [mineral lease] signing-bonus check, only to be pulled aside by the teller” and told that he was actually depositing a million dollar check.\n\nAt that moment, I realized what the Eagle Ford Shale meant to the people of South Texas: an imagined opportunity to break from the risky, agriculturally based lifestyles of the past. But when I looked out the window at the speeding big-rigs, I wondered to myself where that money was actually going? Yes, some economic benefits were chasing those heedless truck drivers. And, at least according to some of the locals, there really were Jed Clampett-style stories of impoverished ranchers overwhelmed by their first mineral royalty checks. But there had to be more to this story. It was evident that the economic benefits were not evenly distributed across the rugged South Texas landscape. (Read <a href=\"http://www.gpsctamu.org/research-spotlight.html#vol3iss2\">more</a>)\n\n(Pictured: Trey Murphy on the left with a companion.)")

issue_9_6.articles.create(
    :title => "Calendar at a Glance", 
    :order_number => 8, 
    :image_url => "", 
    :content => "<ul>\n    <li>Oct 03: AGPCC & YPA - Bring Your Dog Event @ The Backyard</li>\n    <li>Oct 04: GPSC - General Assembly Meeting</li>\n    <li>Oct 04: Silver Taps</li>\n    <li>Oct 06: MSC Town Hall - Lunchbox Series: The Cover Letter</li>\n    <li>Oct 07: All-Corps Run</li>\n    <li>Oct 07: ISA - Football Weekend with C.A.D.E.T.</li>\n    <li>Oct 07: MSC Aggie Cinema - The Secret Life of Pets</li>\n    <li>Oct 08: ISA - Football Weekend with C.A.D.E.T.</li>\n    <li>Oct 08: Texas A&M vs. Tennessee (Football)</li>\n    <li>Oct 09: MSC Town Hall - Ben Rector in Concert</li>\n    <li>Oct 11: MSC CAMAC - Student Conference On Latino Affairs Informational</li>\n    <li>Oct 12: AGPCC Freshly Fit Nutrition and Exercise Class</li>\n    <li>Oct 13: MSC OPAS - The Capitol Steps</li>\n    <li>Oct 13: MSC Town Hall - Lunchbox Series: NeonNoah</li>\n    <li>Oct 15: MSC OPAS - Daniel Tiger's Neighborhood Live!</li>\n</ul>")

issue_9_6.articles.create(
    :title => "About the Nth Degree", 
    :order_number => 9, 
    :image_url => "", 
    :content => "Nth Degree is an e-mail newsletter publication of the Graduate and Professional Student Council (GPSC) that is published on the Monday of each week. Founded in 2008, the newsletter serves as the source of news written by graduate and professional students, and delivered for graduate and professional students. Articles for the Nth Degree are welcome by students of the graduate and professional student council. All correspondence with regards to the Nth Degree should be directed to Paul Taele at <a href=\"mailto:president@gpsc.tamu.edu\">president@gpsc.tamu.edu</a>.")